---
stages:
  - lint
  - rspec
  - build

.ruby_docker_template: &ruby_docker_template
  before_script:
    - bundle --version
    - bundle install
  image: ruby:latest

rubocop:
  stage: lint
  <<: *ruby_docker_template
  script:
   - ruby --version
   - rubocop --version
   - rubocop
  tags:
    - ruby

rspec:
  stage: rspec
  <<: *ruby_docker_template
  script:
   - ruby --version
   - rspec --version
   - rake spec
  tags:
    - ruby

gem_build:
  stage: build
  <<: *ruby_docker_template
  script:
   - ruby --version
   - gem --version
   - gem build tp_link_smartplug.gemspec
  tags:
    - ruby
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    when: on_success
    expire_in: 3 days
    paths:
      - '*.gem'
...