language: ruby
cache: bundler
os:
- linux
rvm:
- 2.5.5
- 2.6.3
install:
- bundle install
before_script:
- ruby --version
- bundle --version
script: rake test
jobs:
  include:
  - stage: Build
    name: Build
    rvm: 2.6.3
    script: rake build
    if: branch = master
  - stage: Rubygem Release
    if: tag IS present
    deploy:
      provider: rubygems
      api_key:
        secure: dDJFB+Bp9/66bC1yY0vFr67TMe5UpuHJZagnn9Nzx+Z8o9ijPpujGpV9fku+imE/MypjpPNLMb/YFZFwc69ZgRJxFk3vOVnj7Vt33PlwPk51S/iYbYPJcG6MmcbWCGoQC5/GhRd2Kx9AE1k0XVG3fOnJuzRd/alRl7KoDu4l5NtNHOy/IKNWBnM4bEaS+vP2Lpgecoxm6JYHVLtackz85jktvBDn1ls0oqPP0sY/9/MsJJPtHlKpOOCm1C5q+TVmd/IVmbKt1tecYCTj017POrGrN/brpTLHbObjkf01FxS1r0hJjLE1nfRHZHFznaSOowAZZGnR/CuEIKlM6HM3oQ3+wiYBNWM+YeBr+4pfBp/8oOYiVk0SJuO2RCOmeURFyBBjyL3vFzE4uG8Avp9ChOHB9921raFVES087L1lHUnMcYwQ2mIC1iT7A0yNWTidCfPZt6Hpv2BOIJbvnbtOHMGI1sZVCzlmG+jDL/DE81MynNPR6EchFSuqHR4hEZ6CsIvfDuN+2vIIPSAvoYCtowgEvb9xFTRICNx9llga6HiyOALDJnY5zPbytG4qp7kmYE5lhgaBtgi0uPYCiAtwza04DDWHvCT871ThZM4XYIGQq0Fr6SBMaYmR1LG59fooIKb3TocpFCaCRoAeWQXi8q2pxSUjVKUpM95RuZkzK+Y=
      gem: tp_link_smartplug
      on:
        tags: true
        repo: bmhughes/tp_link_smartplug
  - stage: Github Release
    if: tag IS present
    deploy:
      provider: releases
      api_key:
        secure: oIdMZ93YAc8HbUOrEH7vACknlMA+6bPg5bp8pifQTX/h4nUhv9S9VEAmES3/6gMpL40tUgqqzflkb4SBBYSn41PUd0MTpmeJ/kDBmoYpGovgjrLnL0gsIPfjotzFX2ninYUtkd935IkugVqKuHr9x2NwDV/xueKt3W1VUdR5qh5ZHnmaYS3djc3uXnU2n34KxtpBCwrgmyW2n7okjC4TGEvDME+TzIIgNXaJToVuUcy8D2FLLZBxEb6td3pizuI4mnqi0C8/LrtFpy4Q7/rURyJaIZ1UT2bHaXcCYxrrkEjICE+34yFild4pYSp69Obfih2WReA4vafDMF3J+6T4IaYOaLss90f5RsOey1Edia4jeFWsul+xYvPQXfvYZU1M+QCqyBiFDuDGDriexcVj9xoe35UNAvDuGyi5IORjIjT5T9CgRvdHrojHSxfR0YuENffPpwuUTYnYPyCBuHUCAtqjj5l28IIvzxn7F8d92Nip7OYLeVEFzWi+B8jOMwB1JIC/U7IEKXKZYqQG6QM/slPNd8KAUQKKmPxRErWsfCvMdcvYTSA+t7QbIRxBcN/tkJtuNuD1g3ZG2w6h3SUAm5dAFewqx9oNpC0j9BHOAGBY3fTWw9pcETGjjoQyaVsnSscWPCPYugtOlsk1g7yc6v5yn+yHuC7VQOqxIkeJ6h4=
      file_glob: true
      file: "*.gem"
      on:
        tags: true
        repo: bmhughes/tp_link_smartplug
