---
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rubocop checks
        uses: bmhughes/rubocop-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
    name: Test - Ruby ${{ matrix.ruby }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Rake Test - Ruby ${{ matrix.ruby }}
        run: |
          ruby -v
          gem install bundler
          bundle install
          rake test

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Rake Build
        run: |
          ruby -v
          gem install bundler
          bundle install
          rake clean test build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gem-file
          path: pkg/*.gem
          retention-days: 5

      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/
          retention-days: 3
...
